/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Student = IDL.Record({
  'branch' : IDL.Text,
  'semester' : IDL.Nat,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'rollNumber' : IDL.Text,
  'course' : IDL.Text,
});
export const Subject = IDL.Record({
  'branch' : IDL.Text,
  'semester' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
});
export const Mark = IDL.Record({
  'markType' : IDL.Text,
  'markValue' : IDL.Nat,
  'markQuestion' : IDL.Text,
});
export const MarkStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Draft' : IDL.Null,
  'Submitted' : IDL.Null,
});
export const MidMarks = IDL.Record({
  'marks' : IDL.Vec(Mark),
  'status' : MarkStatus,
  'creator' : IDL.Principal,
  'subject' : Subject,
  'midExam' : IDL.Text,
  'student' : Student,
});
export const AppRole = IDL.Variant({
  'HOD' : IDL.Null,
  'ClassTeacher' : IDL.Null,
  'SubjectFaculty' : IDL.Null,
  'Student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'branch' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'appRole' : AppRole,
  'section' : IDL.Opt(IDL.Text),
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Principal),
      ],
      [],
      [],
    ),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'approveMidMarks' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMidMarks' : IDL.Func([Student, Subject, IDL.Text], [IDL.Text], []),
  'getAllMarks' : IDL.Func([], [IDL.Vec(MidMarks)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMarksByBranchSectionSemesterSubject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(MidMarks)],
      ['query'],
    ),
  'getMidMarks' : IDL.Func([IDL.Text], [MidMarks], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'getStudentsByBranchSectionSemester' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'getSubject' : IDL.Func([IDL.Text], [Subject], ['query']),
  'getUserProfilePublic' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectMidMarks' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitMidMarks' : IDL.Func([IDL.Text], [], []),
  'updateMidMarks' : IDL.Func([IDL.Text, IDL.Vec(Mark)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Student = IDL.Record({
    'branch' : IDL.Text,
    'semester' : IDL.Nat,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'rollNumber' : IDL.Text,
    'course' : IDL.Text,
  });
  const Subject = IDL.Record({
    'branch' : IDL.Text,
    'semester' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
  });
  const Mark = IDL.Record({
    'markType' : IDL.Text,
    'markValue' : IDL.Nat,
    'markQuestion' : IDL.Text,
  });
  const MarkStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Draft' : IDL.Null,
    'Submitted' : IDL.Null,
  });
  const MidMarks = IDL.Record({
    'marks' : IDL.Vec(Mark),
    'status' : MarkStatus,
    'creator' : IDL.Principal,
    'subject' : Subject,
    'midExam' : IDL.Text,
    'student' : Student,
  });
  const AppRole = IDL.Variant({
    'HOD' : IDL.Null,
    'ClassTeacher' : IDL.Null,
    'SubjectFaculty' : IDL.Null,
    'Student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'branch' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'appRole' : AppRole,
    'section' : IDL.Opt(IDL.Text),
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Principal),
        ],
        [],
        [],
      ),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'approveMidMarks' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMidMarks' : IDL.Func([Student, Subject, IDL.Text], [IDL.Text], []),
    'getAllMarks' : IDL.Func([], [IDL.Vec(MidMarks)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMarksByBranchSectionSemesterSubject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(MidMarks)],
        ['query'],
      ),
    'getMidMarks' : IDL.Func([IDL.Text], [MidMarks], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'getStudentsByBranchSectionSemester' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'getSubject' : IDL.Func([IDL.Text], [Subject], ['query']),
    'getUserProfilePublic' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectMidMarks' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitMidMarks' : IDL.Func([IDL.Text], [], []),
    'updateMidMarks' : IDL.Func([IDL.Text, IDL.Vec(Mark)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };