/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'HOD' : null } |
  { 'ClassTeacher' : null } |
  { 'SubjectFaculty' : null } |
  { 'Student' : null };
export interface Mark {
  'markType' : string,
  'markValue' : bigint,
  'markQuestion' : string,
}
export type MarkStatus = { 'Approved' : null } |
  { 'Draft' : null } |
  { 'Submitted' : null };
export interface MidMarks {
  'marks' : Array<Mark>,
  'status' : MarkStatus,
  'creator' : Principal,
  'subject' : Subject,
  'midExam' : string,
  'student' : Student,
}
export interface Student {
  'branch' : string,
  'semester' : bigint,
  'name' : string,
  'section' : string,
  'rollNumber' : string,
  'course' : string,
}
export interface Subject {
  'branch' : string,
  'semester' : bigint,
  'code' : string,
  'name' : string,
}
export interface UserProfile {
  'branch' : [] | [string],
  'username' : string,
  'appRole' : AppRole,
  'section' : [] | [string],
  'passwordHash' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<
    [string, string, string, string, bigint, string, [] | [Principal]],
    undefined
  >,
  'addSubject' : ActorMethod<[string, string, string, bigint], undefined>,
  'approveMidMarks' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMidMarks' : ActorMethod<[Student, Subject, string], string>,
  'getAllMarks' : ActorMethod<[], Array<MidMarks>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarksByBranchSectionSemesterSubject' : ActorMethod<
    [string, string, bigint, string],
    Array<MidMarks>
  >,
  'getMidMarks' : ActorMethod<[string], MidMarks>,
  'getStudent' : ActorMethod<[string], Student>,
  'getStudentsByBranchSectionSemester' : ActorMethod<
    [string, string, bigint],
    Array<Student>
  >,
  'getSubject' : ActorMethod<[string], Subject>,
  'getUserProfilePublic' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectMidMarks' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitMidMarks' : ActorMethod<[string], undefined>,
  'updateMidMarks' : ActorMethod<[string, Array<Mark>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];